### ISSUE TITLE
Query authoritative DNS Server for SRV record

### ISSUE THREAD

**Issue by mpldr** [matrix-org/matrix-federation-tester#145]
It would be great if the tester could check against a domain's authoritative dns server instead of a caching one, so the result updates in real-time.

Sorry for the update spam… got slippery fingers today.

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-federation-tester/pull/135 appears to have been an attempt to implement this.

As I said there: this isn't easy to do right, and I'm not entirely convinced that this is something we should support in the federation tester. 

Even an authoritative DNS server might actually just be caching the results from another upstream server, so there are no guarantees. In general, you're better off using short TTLs while experimenting with this stuff rather than relying on tooling to circumvent caches.
